/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_workspace_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue Health Check */
        post: operations["enqueue_health_check_jobs_health_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Result */
        get: operations["get_job_result_jobs__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Bases */
        get: operations["list_knowledge_bases_knowledge_bases_get"];
        put?: never;
        /** Create Knowledge Base */
        post: operations["create_knowledge_base_knowledge_bases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Base */
        get: operations["get_knowledge_base_knowledge_bases__kb_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Text */
        post: operations["ingest_text_knowledge_bases__kb_id__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_knowledge_bases__kb_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/synthesize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Synthesize
         * @description Regenerate the KB's knowledge artifacts (overview/gotchas/glossary + gaps), in background.
         */
        post: operations["synthesize_knowledge_bases__kb_id__synthesize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Knowledge Base
         * @description Download a knowledge-transfer report for the KB (Markdown or print-ready HTML).
         */
        get: operations["export_knowledge_base_knowledge_bases__kb_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Onboarding
         * @description Guided successor reading path over the KB's synthesized knowledge (plan §13.16).
         *
         *     Returns `ready=False` with no steps when nothing has been synthesized yet.
         */
        get: operations["get_onboarding_knowledge_bases__kb_id__onboarding_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/unanswered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Unanswered
         * @description Questions the oracle abstained on for this KB — the gaps worth capturing next.
         */
        get: operations["list_unanswered_knowledge_bases__kb_id__unanswered_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/knowledge-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Items */
        get: operations["list_knowledge_items_knowledge_bases__kb_id__knowledge_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Employees */
        get: operations["list_employees_employees_get"];
        put?: never;
        /** Create Employee */
        post: operations["create_employee_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employee */
        get: operations["get_employee_employees__employee_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Employee */
        patch: operations["update_employee_employees__employee_id__patch"];
        trace?: never;
    };
    "/employees/{employee_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Status */
        post: operations["change_status_employees__employee_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{source_type}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_connectors__source_type__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{source_type}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Callback */
        get: operations["oauth_callback_connectors__source_type__callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/sources/{source_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_connectors_sources__source_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-bases/{kb_id}/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_knowledge_bases__kb_id__interviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{interview_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Interview */
        get: operations["get_interview_interviews__interview_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{interview_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer */
        post: operations["answer_interviews__interview_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{interview_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish */
        post: operations["finish_interviews__interview_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analytics */
        get: operations["get_analytics_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Risk */
        get: operations["get_knowledge_risk_knowledge_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsDayOut */
        AnalyticsDayOut: {
            /** Date */
            date: string;
            /** Questions */
            questions: number;
            /** Abstained */
            abstained: number;
        };
        /** AnalyticsOut */
        AnalyticsOut: {
            /** Total Questions */
            total_questions: number;
            /** Answered */
            answered: number;
            /** Abstained */
            abstained: number;
            /** Abstention Rate */
            abstention_rate: number;
            /** Kbs Total */
            kbs_total: number;
            /** Kbs Ready */
            kbs_ready: number;
            /** Coverage */
            coverage: number;
            /** Artifacts Total */
            artifacts_total: number;
            /** Interviews Total */
            interviews_total: number;
            /** Timeseries */
            timeseries: components["schemas"]["AnalyticsDayOut"][];
            /** Top Kbs */
            top_kbs: components["schemas"]["AnalyticsTopKbOut"][];
        };
        /** AnalyticsTopKbOut */
        AnalyticsTopKbOut: {
            /**
             * Knowledge Base Id
             * Format: uuid
             */
            knowledge_base_id: string;
            /** Subject */
            subject: string;
            /** Questions */
            questions: number;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /**
         * Citation
         * @description A reference back to a retrieved chunk that supports the answer.
         */
        Citation: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
            /** Snippet */
            snippet?: string | null;
        };
        /** ConnectStartResponse */
        ConnectStartResponse: {
            /** Auth Url */
            auth_url: string;
        };
        /** DashboardConnector */
        DashboardConnector: {
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Employee Count */
            employee_count: number;
            /** Last Synced At */
            last_synced_at?: string | null;
        };
        /** DashboardJob */
        DashboardJob: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Subject */
            subject?: string | null;
        };
        /** DashboardKpis */
        DashboardKpis: {
            /** On Notice */
            on_notice: number;
            /** Departing Soon */
            departing_soon: number;
            /** Kbs Ready */
            kbs_ready: number;
            /** Kbs Total */
            kbs_total: number;
            /** Jobs Running */
            jobs_running: number;
            /** Needs Attention */
            needs_attention: number;
        };
        /** DashboardOut */
        DashboardOut: {
            kpis: components["schemas"]["DashboardKpis"];
            /** On Notice */
            on_notice: components["schemas"]["DashboardPerson"][];
            /** Connectors */
            connectors: components["schemas"]["DashboardConnector"][];
            /** Active Jobs */
            active_jobs: components["schemas"]["DashboardJob"][];
        };
        /** DashboardPerson */
        DashboardPerson: {
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Notice End Date */
            notice_end_date?: string | null;
            /** Knowledge Base Id */
            knowledge_base_id?: string | null;
            /** Capture Progress */
            capture_progress: number;
        };
        /** DeptRiskOut */
        DeptRiskOut: {
            /** Department */
            department: string;
            /** People */
            people: number;
            /** At Risk */
            at_risk: number;
            /** Avg Capture */
            avg_capture: number;
            /** Risk */
            risk: string;
        };
        /** EmployeeCreate */
        EmployeeCreate: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Title */
            title?: string | null;
            /** Github Username */
            github_username?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /**
             * Connectors
             * @default []
             */
            connectors: string[];
        };
        /**
         * EmployeeDetailOut
         * @description Employee plus their knowledge base id and connected sources (for the detail view).
         */
        EmployeeDetailOut: {
            employee: components["schemas"]["EmployeeOut"];
            /** Knowledge Base Id */
            knowledge_base_id?: string | null;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["SourceOut"][];
        };
        /** EmployeeOut */
        EmployeeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Title */
            title?: string | null;
            /** Github Username */
            github_username?: string | null;
            /** Status */
            status: string;
            /**
             * Connectors
             * @default []
             */
            connectors: string[];
            /** Notice End Date */
            notice_end_date?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EmployeeStatusUpdate */
        EmployeeStatusUpdate: {
            /** Status */
            status: string;
        };
        /** EmployeeUpdate */
        EmployeeUpdate: {
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Title */
            title?: string | null;
            /** Github Username */
            github_username?: string | null;
            /** Connectors */
            connectors?: string[] | null;
        };
        /**
         * GroundedAnswer
         * @description The oracle's contract object (plan §7). Always returned by the grounded-answer path.
         */
        GroundedAnswer: {
            /** Answer */
            answer: string;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /**
             * Abstained
             * @default false
             */
            abstained: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Environment */
            environment: string;
        };
        /** IngestTextRequest */
        IngestTextRequest: {
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Url */
            url?: string | null;
        };
        /** InterviewAnswerRequest */
        InterviewAnswerRequest: {
            /** Answer */
            answer: string;
        };
        /** InterviewDetailOut */
        InterviewDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["InterviewMessageOut"][];
        };
        /** InterviewFinishResponse */
        InterviewFinishResponse: {
            /** Indexed Answers */
            indexed_answers: number;
            /** Chunks */
            chunks: number;
        };
        /** InterviewMessageOut */
        InterviewMessageOut: {
            /** Role */
            role: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** InterviewQuestionResponse */
        InterviewQuestionResponse: {
            /** Question */
            question: string;
        };
        /** InterviewStartResponse */
        InterviewStartResponse: {
            /**
             * Interview Id
             * Format: uuid
             */
            interview_id: string;
            /** Question */
            question: string;
        };
        /** JobEnqueuedResponse */
        JobEnqueuedResponse: {
            /** Task Id */
            task_id: string;
        };
        /** JobResultResponse */
        JobResultResponse: {
            /** Task Id */
            task_id: string;
            /** Ready */
            ready: boolean;
            /**
             * Failed
             * @default false
             */
            failed: boolean;
            /** Result */
            result?: string | null;
        };
        /** KnowledgeBaseCreate */
        KnowledgeBaseCreate: {
            /** Subject Person Name */
            subject_person_name: string;
        };
        /**
         * KnowledgeBaseDetailOut
         * @description A single KB plus its linked employee (for the KB workspace subject header).
         */
        KnowledgeBaseDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Subject Person Name */
            subject_person_name: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            employee?: components["schemas"]["EmployeeOut"] | null;
        };
        /** KnowledgeBaseOut */
        KnowledgeBaseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Subject Person Name */
            subject_person_name: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** KnowledgeItemOut */
        KnowledgeItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** KnowledgeRiskOut */
        KnowledgeRiskOut: {
            /** Org Risk Score */
            org_risk_score: number;
            /** Critical */
            critical: number;
            /** High */
            high: number;
            /** People At Risk */
            people_at_risk: number;
            /** People */
            people: components["schemas"]["RiskPersonOut"][];
            /** Departments */
            departments: components["schemas"]["DeptRiskOut"][];
            /** Spofs */
            spofs: components["schemas"]["RiskPersonOut"][];
        };
        /** MemberOut */
        MemberOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** External User Id */
            external_user_id: string;
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Role */
            role: string;
        };
        /** OnboardingStepOut */
        OnboardingStepOut: {
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Intro */
            intro: string;
            /** Body */
            body: string;
            /** Read Minutes */
            read_minutes: number;
        };
        /** OnboardingViewOut */
        OnboardingViewOut: {
            /**
             * Knowledge Base Id
             * Format: uuid
             */
            knowledge_base_id: string;
            /** Subject Person Name */
            subject_person_name: string;
            /** Subject Title */
            subject_title?: string | null;
            /** Source Count */
            source_count: number;
            /** Interview Count */
            interview_count: number;
            /**
             * Steps
             * @default []
             */
            steps: components["schemas"]["OnboardingStepOut"][];
            /** Total Read Minutes */
            total_read_minutes: number;
            /** Ready */
            ready: boolean;
        };
        /** RiskPersonOut */
        RiskPersonOut: {
            /**
             * Employee Id
             * Format: uuid
             */
            employee_id: string;
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Department */
            department: string;
            /** Status */
            status: string;
            /** Capture */
            capture: number;
            /** Risk */
            risk: string;
            /** Knowledge Base Id */
            knowledge_base_id?: string | null;
        };
        /** SourceOut */
        SourceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Last Synced At */
            last_synced_at?: string | null;
        };
        /**
         * UnansweredQuestionOut
         * @description A question the oracle couldn't answer (abstained), grouped — a capture-worthy gap.
         */
        UnansweredQuestionOut: {
            /** Question */
            question: string;
            /** Count */
            count: number;
            /**
             * Last Asked
             * Format: date-time
             */
            last_asked: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkspaceContextOut
         * @description Workspace-scoped data returned to a logged-in user (Phase 0 DoD endpoint).
         */
        WorkspaceContextOut: {
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Workspace Name */
            workspace_name: string;
            /** Pinecone Namespace */
            pinecone_namespace: string;
            member: components["schemas"]["MemberOut"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_me_workspace_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceContextOut"];
                };
            };
        };
    };
    enqueue_health_check_jobs_health_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueuedResponse"];
                };
            };
        };
    };
    get_job_result_jobs__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_bases_knowledge_bases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseOut"][];
                };
            };
        };
    };
    create_knowledge_base_knowledge_bases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeBaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_base_knowledge_bases__kb_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_text_knowledge_bases__kb_id__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueuedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_knowledge_bases__kb_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundedAnswer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    synthesize_knowledge_bases__kb_id__synthesize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueuedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_knowledge_base_knowledge_bases__kb_id__export_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_onboarding_knowledge_bases__kb_id__onboarding_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingViewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_unanswered_knowledge_bases__kb_id__unanswered_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnansweredQuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_items_knowledge_bases__kb_id__knowledge_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_employees_employees_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeOut"][];
                };
            };
        };
    };
    create_employee_employees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_employee_employees__employee_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_employee_employees__employee_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_employees__employee_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_connectors__source_type__start_post: {
        parameters: {
            query: {
                employee_id: string;
            };
            header?: never;
            path: {
                source_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_callback_connectors__source_type__callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path: {
                source_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_connectors_sources__source_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueuedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_knowledge_bases__kb_id__interviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interview_interviews__interview_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_interviews__interview_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_interviews__interview_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewFinishResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    get_analytics_analytics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOut"];
                };
            };
        };
    };
    get_knowledge_risk_knowledge_risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRiskOut"];
                };
            };
        };
    };
}
